// src/lib/components/hero/Hero.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import type { HeroData } from "$lib/data/hero";
	import HeroBackground from "./HeroBackground.svelte";
	import HeroTitle from "./HeroTitle.svelte";
	import HeroStats from "./HeroStats.svelte";
	import HeroImage from "./HeroImage.svelte";
	import Reveal from "$lib/components/shared/Reveal.svelte";

	interface Props {
		hero: HeroData;
		onBookCall: () => void;
	}

	let { hero, onBookCall }: Props = $props();

	let scrollY = $state(0);
	let blurPx = $derived(Math.min(16, (scrollY / 480) * 16));
	let opacity = $derived(Math.max(0, 1 - scrollY / 420));
	let scale = $derived(Math.max(0.92, 1 - (scrollY / 1000) * 0.08));
	let translateY = $derived(-(scrollY * 0.1));

	onMount(() => {
		function handleScroll() {
			scrollY = window.scrollY;
		}

		window.addEventListener("scroll", handleScroll, { passive: true });
		return () => {
			window.removeEventListener("scroll", handleScroll);
		};
	});
</script>

<section
	id="hero"
	class="fixed inset-0 z-0 h-[100dvh] w-full overflow-hidden bg-white dark:bg-black"
>
	<!-- BACKGROUND -->
	<HeroBackground />

	<!-- SCROLL TRANSFORM WRAPPER -->
	<div
		class="relative h-full w-full will-change-transform"
		style="filter: blur({blurPx}px); opacity: {opacity}; transform: scale({scale}) translateY({translateY}px); transform-origin: center center;"
	>
		<div
			class="relative mx-auto h-full w-full max-w-[1560px] px-[5.5vw] lg:px-[5vw] xl:px-[4.5vw]"
		>
			<div class="relative flex h-full w-full items-center">
				<!-- LEFT CONTENT -->
				<div class="relative z-20 flex w-full lg:w-[55%] flex-col text-left">
					<!-- NAME + ROLE -->
					<Reveal delay={0.08}>
						<div class="w-fit">
							<HeroTitle title={hero.preHeading || "ANMOL MADAN"} />

							<!-- ROLE -->
							<p
								class="mt-0 break-words sm:whitespace-nowrap pl-[3px] text-[clamp(11px,0.9vw,15px)] font-semibold uppercase leading-[1.2] sm:leading-[1] tracking-[0.18em] sm:tracking-[0.34em] text-neutral-500 dark:text-neutral-400"
							>
								Cybersecurity SPECIALIST
								<span class="mx-[6px] sm:mx-[8px]">·</span>
								Motivational Speaker
							</p>
						</div>
					</Reveal>

					<!-- DESCRIPTION -->
					<Reveal delay={0.2}>
						<p
							class="mt-[32px] max-w-[clamp(430px,31vw,580px)] text-[clamp(13px,0.95vw,17px)] leading-[1.6] text-neutral-600 dark:text-neutral-400 [text-align:justify] [text-justify:inter-word]"
						>
							{hero.description}
						</p>
					</Reveal>

					<!-- STATS -->
					<Reveal delay={0.26}>
						<div class="mt-[14px]">
							<HeroStats stats={hero.stats} />
						</div>
					</Reveal>

					<!-- BUTTONS -->
					<Reveal delay={0.32}>
						<div class="mt-[18px] flex items-center gap-[clamp(10px,1vw,16px)]">
							<!-- BOOK A CALL -->
							<button
								type="button"
								onclick={onBookCall}
								class="inline-flex items-center justify-center rounded-full bg-neutral-950 px-[clamp(20px,1.8vw,28px)] py-[clamp(10px,0.9vh,14px)] text-[clamp(10px,0.65vw,12px)] font-semibold uppercase tracking-[0.12em] text-white shadow-sm transition-all duration-200 hover:bg-neutral-800 active:scale-95 dark:bg-white dark:text-black dark:hover:bg-neutral-200 cursor-pointer"
							>
								{hero.buttonText || "Book a Call"}
							</button>

							<!-- LEARN MORE -->
							<a
								href="#about"
								class="inline-flex items-center justify-center rounded-full border border-neutral-300 bg-transparent px-[clamp(20px,1.8vw,28px)] py-[clamp(10px,0.9vh,14px)] text-[clamp(10px,0.65vw,12px)] font-medium uppercase tracking-[0.12em] text-neutral-700 transition-all duration-200 hover:border-black hover:text-black active:scale-95 dark:border-neutral-700 dark:text-neutral-300 dark:hover:border-white dark:hover:text-white"
							>
								Learn More
							</a>
						</div>
					</Reveal>
				</div>

				<!-- RIGHT IMAGE AREA -->
				<div
					style="transform: translate(-30px, calc(-50% + 100px));"
					class="absolute right-[-4%] sm:right-[0%] lg:right-[2%] top-1/2 z-10 h-[72%] sm:h-[80%] lg:h-[82%] w-[55%] sm:w-[48%] lg:w-[45%] opacity-30 sm:opacity-60 lg:opacity-100 pointer-events-none lg:pointer-events-auto transition-opacity duration-300"
				>
					<HeroImage
						heroImage={hero.heroImage}
						fallbackHeroImage={hero.fallbackHeroImage}
						alt={hero.preHeading || "Anmol Madan"}
					/>
				</div>
			</div>
		</div>
	</div>
</section>

// src/components/visitor/hero/Hero.tsx
import { getHero } from "@/services/hero/hero.service";

import Reveal from "@/components/shared/Reveal";
import CalButton from "@/components/shared/CalButton";

import HeroScrollWrapper from "./HeroScrollWrapper";
import HeroBackground from "./HeroBackground";
import HeroImage from "./HeroImage";
import HeroStats from "./HeroStats";
import HeroTitle from "./HeroTitle";

/* ==========================================================
   STRUCTURED 2-COLUMN HERO
========================================================== */

interface HeroProps {
  hero?: any;
}

export default async function Hero({ hero: initialHero }: HeroProps = {}) {
  const hero = initialHero !== undefined ? initialHero : await getHero();

  if (!hero) return null;

  /* ==========================================================
     STATS
  ========================================================== */

  const stats = [
    {
      number: hero.stat_1_number,
      label: hero.stat_1_label,
    },
    {
      number: hero.stat_2_number,
      label: hero.stat_2_label,
    },
    {
      number: hero.stat_3_number,
      label: hero.stat_3_label,
    },
  ];

  /* ==========================================================
     ROLE
  ========================================================== */

  const roleSubtitle =
    "Cybersecurity SPECIALIST · Motivational Speaker";

  /* ==========================================================
     RENDER
  ========================================================== */

  return (
    <section
      id="hero"
      className="
        fixed
        inset-0
        z-0
        h-[100dvh]
        w-full
        overflow-hidden
        bg-white
        dark:bg-black
      "
    >
      {/* ======================================================
          BACKGROUND
      ====================================================== */}

      <HeroBackground />

      {/* ======================================================
          HERO SCROLL CONTAINER
      ====================================================== */}

      <HeroScrollWrapper>
        {/* ==================================================
            FIXED PROPORTIONAL CANVAS
        ================================================== */}

        <div
          className="
            relative
            mx-auto
            h-full
            w-full
            max-w-[1560px]
            px-[5.5vw]
            lg:px-[5vw]
            xl:px-[4.5vw]
          "
        >
          <div
            className="
              relative
              flex
              h-full
              w-full
              items-center
            "
          >
            {/* ==================================================
                LEFT CONTENT
            ================================================== */}

            <div
              className="
                relative
                z-20
                flex
                w-full
                lg:w-[55%]
                flex-col
                text-left
              "
            >
              {/* ==================================================
                  NAME + ROLE
              ================================================== */}

              <Reveal delay={0.08}>
                <div className="w-fit">
                  {/* ==================================================
                      NAME
                  ================================================== */}

                  <HeroTitle
                    title={
                      hero.pre_heading ||
                      "ANMOL MADAN"
                    }
                  />

                  {/* ==================================================
                      ROLE

                      ZERO GAP AFTER NAME
                      EXTENDED HORIZONTAL LENGTH
                  ================================================== */}

                  <p
                    className="
                      mt-0
                      break-words
                      sm:whitespace-nowrap
                      pl-[3px]
                      text-[clamp(11px,0.9vw,15px)]
                      font-semibold
                      uppercase
                      leading-[1.2]
                      sm:leading-[1]
                      tracking-[0.18em]
                      sm:tracking-[0.34em]
                      text-neutral-500
                      dark:text-neutral-400
                    "
                  >
                    Cybersecurity SPECIALIST
                    <span className="mx-[6px] sm:mx-[8px]">·</span>
                    Motivational Speaker
                  </p>
                </div>
              </Reveal>

              {/* ==================================================
                  DESCRIPTION

                  CLEAR SPACE AFTER ROLE
              ================================================== */}

              <Reveal delay={0.2}>
                <p
                  className="
                    mt-[32px]
                    max-w-[clamp(430px,31vw,580px)]
                    text-[clamp(13px,0.95vw,17px)]
                    leading-[1.6]
                    text-neutral-600
                    dark:text-neutral-400
                    [text-align:justify]
                    [text-justify:inter-word]
                  "
                >
                  {hero.description}
                </p>
              </Reveal>

              {/* ==================================================
                  STATS

                  CLEAR SPACE AFTER DESCRIPTION
              ================================================== */}

              <Reveal delay={0.26}>
                <div className="mt-[14px]">
                  <HeroStats stats={stats} />
                </div>
              </Reveal>

              {/* ==================================================
                  BUTTONS

                  CLEAR SPACE AFTER STATS
              ================================================== */}

              <Reveal delay={0.32}>
                <div
                  className="
                    mt-[14px]
                    flex
                    items-center
                    gap-[clamp(10px,1vw,16px)]
                  "
                >
                  {/* ==================================================
                      BOOK A CALL
                  ================================================== */}

                  <CalButton
                    className="
                      inline-flex
                      items-center
                      justify-center
                      rounded-full
                      bg-neutral-950
                      px-[clamp(20px,1.8vw,28px)]
                      py-[clamp(10px,0.9vh,14px)]
                      text-[clamp(10px,0.65vw,12px)]
                      font-semibold
                      uppercase
                      tracking-[0.12em]
                      text-white
                      shadow-sm
                      transition-all
                      duration-200
                      hover:bg-neutral-800
                      active:scale-95
                      dark:bg-white
                      dark:text-black
                      dark:hover:bg-neutral-200
                    "
                  >
                    Book a Call
                  </CalButton>

                  {/* ==================================================
                      LEARN MORE
                  ================================================== */}

                  <a
                    href="#about"
                    className="
                      inline-flex
                      items-center
                      justify-center
                      rounded-full
                      border
                      border-neutral-300
                      bg-transparent
                      px-[clamp(20px,1.8vw,28px)]
                      py-[clamp(10px,0.9vh,14px)]
                      text-[clamp(10px,0.65vw,12px)]
                      font-medium
                      uppercase
                      tracking-[0.12em]
                      text-neutral-700
                      transition-all
                      duration-200
                      hover:border-black
                      hover:text-black
                      active:scale-95
                      dark:border-neutral-700
                      dark:text-neutral-300
                      dark:hover:border-white
                      dark:hover:text-white
                    "
                  >
                    Learn More
                  </a>
                </div>
              </Reveal>
            </div>

            {/* ==================================================
                RIGHT IMAGE AREA
            ================================================== */}

            <div
              style={{ transform: "translate(-30px, calc(-50% + 100px))" }}
              className="
                absolute
                right-[-4%]
                sm:right-[0%]
                lg:right-[2%]
                top-1/2
                z-10
                h-[72%]
                sm:h-[80%]
                lg:h-[82%]
                w-[55%]
                sm:w-[48%]
                lg:w-[45%]
                opacity-30
                sm:opacity-60
                lg:opacity-100
                pointer-events-none
                lg:pointer-events-auto
                transition-opacity
                duration-300
              "
            >
              <HeroImage hero={hero} />
            </div>
          </div>
        </div>
      </HeroScrollWrapper>
    </section>
  );
}
