// src/components/visitor/layout/Footer.tsx
"use client";

import { Instrument_Sans } from "next/font/google";
import { Mail, Phone, ArrowUpRight } from "lucide-react";

import CalButton from "@/components/shared/CalButton";
import type { ContactLink } from "@/types/contact";
import { renderContactIcon } from "@/components/shared/ContactIcons";

/* =========================================================
   FONT
========================================================= */

const footerFont = Instrument_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

/* =========================================================
   INLINE ICONS
========================================================= */

function LinkedInIcon({
  className = "h-4 w-4",
}: {
  className?: string;
}) {
  return (
    <svg
      className={className}
      fill="currentColor"
      viewBox="0 0 24 24"
      aria-hidden="true"
    >
      <path d="M19 3a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h14m-.5 15.5v-5.3a3.26 3.26 0 0 0-3.26-3.26c-.85 0-1.84.52-2.28 1.3v-1.11h-2.79v8.37h2.79v-4.93c0-.77.62-1.4 1.39-1.4a1.4 1.4 0 0 1 1.4 1.4v4.93h2.75M6.46 10.9v8.37H9.2V10.9H6.46M7.83 6.45a1.62 1.62 0 0 0-1.63 1.62c0 .9.73 1.63 1.63 1.63a1.63 1.63 0 0 0 1.63-1.63c0-.9-.73-1.62-1.63-1.62Z" />
    </svg>
  );
}

function InstagramIcon({
  className = "h-4 w-4",
}: {
  className?: string;
}) {
  return (
    <svg
      className={className}
      fill="currentColor"
      viewBox="0 0 24 24"
      aria-hidden="true"
    >
      <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.204-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z" />
    </svg>
  );
}

/* =========================================================
   SMOOTH SCROLL
========================================================= */

const scrollToSection = (id: string) => {
  const section = document.querySelector(id);

  if (!section) return;

  section.scrollIntoView({
    behavior: "smooth",
    block: "start",
  });
};

/* =========================================================
   FOOTER
========================================================= */

export default function Footer({
  links = [],
}: {
  links?: ContactLink[];
}) {
  const displayLinks =
    links.length > 0
      ? [
          ...links,
          ...(links.some(
            (link) =>
              link.id?.toLowerCase() === "instagram" ||
              link.icon_name?.toLowerCase() === "instagram"
          )
            ? []
            : [
                {
                  id: "instagram",
                  label: "Instagram",
                  icon_name: "Instagram",
                  url: "https://www.instagram.com/anmolxmadan/",
                },
              ]),
        ]
      : [];

  return (
    <footer
      className={`
        ${footerFont.className}
        border-t
        border-black/[0.08]
        bg-white
        text-black
        dark:border-white/[0.08]
        dark:bg-black
        dark:text-white
      `}
    >
      {/* =====================================================
          PRE-FOOTER CTA
      ===================================================== */}

      <div className="border-b border-white/[0.08] bg-neutral-900 text-white">
        <div
          className="
            mx-auto
            flex
            max-w-[1500px]
            flex-col
            items-start
            justify-between
            gap-8
            px-6
            py-16
            sm:px-8
            lg:flex-row
            lg:items-center
            lg:px-12
            xl:px-16
          "
        >
          <div className="max-w-2xl">
            <span
              className="
                text-[10px]
                font-semibold
                uppercase
                tracking-[0.3em]
                text-neutral-400
              "
            >
              Work Together
            </span>

            <h3
              className="
                mt-3
                text-3xl
                font-medium
                tracking-[-0.03em]
                sm:text-4xl
                lg:text-5xl
              "
            >
              Ready to create an unforgettable
              session?
            </h3>

            <p
              className="
                mt-4
                text-sm
                text-neutral-400
                sm:text-base
              "
            >
              Available for corporate cybersecurity
              training, college workshops, and keynote
              speaking across India & online.
            </p>
          </div>

          {/* =================================================
              BOOK A CALL
          ================================================= */}

          <div className="flex flex-wrap items-center gap-4">
            <CalButton
              className="
                inline-flex
                items-center
                gap-2
                rounded-full
                bg-white
                px-8
                py-4
                text-xs
                font-semibold
                uppercase
                tracking-[0.1em]
                text-black
                transition-all
                duration-300
                hover:scale-105
                hover:bg-neutral-100
                active:scale-95
              "
            >
              Book a Call
              <ArrowUpRight className="h-4 w-4" />
            </CalButton>
          </div>
        </div>
      </div>

      {/* =====================================================
          MAIN FOOTER
      ===================================================== */}

      <div
        className="
          mx-auto
          max-w-[1500px]
          px-6
          py-20
          sm:px-8
          lg:px-12
          xl:px-16
        "
      >
        {/* ===================================================
            FOOTER GRID
        =================================================== */}

        <div
          className="
            grid
            gap-16
            sm:grid-cols-2
            lg:grid-cols-[1.3fr_0.7fr_0.8fr_1fr]
            lg:gap-12
            xl:gap-20
          "
        >
          {/* =================================================
              BRAND
          ================================================= */}

          <div>
            <button
              type="button"
              onClick={() =>
                window.scrollTo({
                  top: 0,
                  behavior: "smooth",
                })
              }
              className="
                group
                cursor-pointer
                border-none
                bg-transparent
                p-0
                text-left
                outline-none
              "
            >
              <h3
                className="
                  text-[26px]
                  font-semibold
                  leading-none
                  tracking-[0.25em]
                  text-black
                  transition-opacity
                  duration-300
                  group-hover:opacity-60
                  dark:text-white
                "
              >
                ANMOL
              </h3>

              <p
                className="
                  mt-1.5
                  text-[8px]
                  font-medium
                  leading-none
                  tracking-[0.48em]
                  text-neutral-400
                "
              >
                MADAN
              </p>
            </button>

            <div
              className="
                mt-8
                max-w-[290px]
                space-y-2
                text-[14px]
                leading-6
                text-neutral-500
                dark:text-neutral-400
              "
            >
              <p
                className="
                  font-medium
                  text-neutral-800
                  dark:text-neutral-200
                "
              >
                Cybersecurity Trainer &
                Motivational Speaker
              </p>

              <p>
                Based in Chandigarh, India
              </p>

              <p>
                Delivering sessions Pan-India &
                Online
              </p>
            </div>
          </div>

          {/* =================================================
              EXPLORE
          ================================================= */}

          <div>
            <h4
              className="
                mb-7
                text-[10px]
                font-semibold
                uppercase
                tracking-[0.28em]
                text-neutral-400
              "
            >
              Explore
            </h4>

            <div
              className="
                flex
                flex-col
                gap-3.5
                text-[14px]
                text-neutral-600
                dark:text-neutral-400
              "
            >
              <button
                type="button"
                onClick={() =>
                  window.scrollTo({
                    top: 0,
                    behavior: "smooth",
                  })
                }
                className="w-fit cursor-pointer border-none bg-transparent p-0 text-left transition-colors duration-300 hover:text-black dark:hover:text-white"
              >
                Home
              </button>

              <button
                type="button"
                onClick={() =>
                  scrollToSection("#about")
                }
                className="w-fit cursor-pointer border-none bg-transparent p-0 text-left transition-colors duration-300 hover:text-black dark:hover:text-white"
              >
                About
              </button>

              <button
                type="button"
                onClick={() =>
                  scrollToSection("#testimonials")
                }
                className="w-fit cursor-pointer border-none bg-transparent p-0 text-left transition-colors duration-300 hover:text-black dark:hover:text-white"
              >
                Testimonials
              </button>

              <button
                type="button"
                onClick={() =>
                  scrollToSection("#services")
                }
                className="w-fit cursor-pointer border-none bg-transparent p-0 text-left transition-colors duration-300 hover:text-black dark:hover:text-white"
              >
                Services
              </button>

              <button
                type="button"
                onClick={() =>
                  scrollToSection("#vision")
                }
                className="w-fit cursor-pointer border-none bg-transparent p-0 text-left transition-colors duration-300 hover:text-black dark:hover:text-white"
              >
                Vision
              </button>

              <button
                type="button"
                onClick={() =>
                  scrollToSection("#note")
                }
                className="w-fit cursor-pointer border-none bg-transparent p-0 text-left transition-colors duration-300 hover:text-black dark:hover:text-white"
              >
                Notes
              </button>
            </div>
          </div>

          {/* =================================================
              KEY EXPERTISE
          ================================================= */}

          <div>
            <h4
              className="
                mb-7
                text-[10px]
                font-semibold
                uppercase
                tracking-[0.28em]
                text-neutral-400
              "
            >
              Key Expertise
            </h4>

            <ul
              className="
                space-y-3.5
                text-[14px]
                leading-6
                text-neutral-600
                dark:text-neutral-400
              "
            >
              <li>Corporate Cybersecurity</li>
              <li>Ethical Hacking Workshops</li>
              <li>Motivational Keynotes</li>
              <li>Executive Threat Defense</li>
              <li>Student Mentorship</li>
            </ul>
          </div>

          {/* =================================================
              CONNECT
          ================================================= */}

          <div>
            <h4
              className="
                mb-7
                text-[10px]
                font-semibold
                uppercase
                tracking-[0.28em]
                text-neutral-400
              "
            >
              Connect Directly
            </h4>

            <div className="flex flex-col gap-4">
              {displayLinks.length > 0 ? (
                displayLinks.map((link) => {
                  const isExternal =
                    !link.url?.startsWith("mailto:") &&
                    !link.url?.startsWith("tel:");

                  return (
                    <a
                      key={link.id}
                      href={link.url}
                      target={
                        isExternal ? "_blank" : undefined
                      }
                      rel={
                        isExternal
                          ? "noopener noreferrer"
                          : undefined
                      }
                      className="
                        flex
                        items-center
                        gap-3
                        text-sm
                        text-neutral-600
                        transition-colors
                        duration-300
                        hover:text-black
                        dark:text-neutral-400
                        dark:hover:text-white
                      "
                    >
                      <div
                        className="
                          flex
                          h-8
                          w-8
                          shrink-0
                          items-center
                          justify-center
                          rounded-full
                          border
                          border-neutral-200
                          bg-neutral-50
                          transition-colors
                          duration-300
                          hover:border-black
                          hover:bg-black
                          hover:text-white
                          dark:border-neutral-800
                          dark:bg-neutral-900
                          dark:hover:border-white
                          dark:hover:bg-white
                          dark:hover:text-black
                        "
                      >
                        {renderContactIcon(
                          link.icon_name,
                          { size: 14 }
                        )}
                      </div>

                      <span className="truncate">
                        {link.label}
                      </span>
                    </a>
                  );
                })
              ) : (
                <>
                  {/* LINKEDIN */}

                  <a
                    href="https://www.linkedin.com/in/anmolmadan7/"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="
                      flex
                      items-center
                      gap-3
                      text-sm
                      text-neutral-600
                      transition-colors
                      duration-300
                      hover:text-black
                      dark:text-neutral-400
                      dark:hover:text-white
                    "
                  >
                    <div
                      className="
                        flex
                        h-8
                        w-8
                        items-center
                        justify-center
                        rounded-full
                        border
                        border-neutral-200
                        bg-neutral-50
                        dark:border-neutral-800
                        dark:bg-neutral-900
                      "
                    >
                      <LinkedInIcon className="h-3.5 w-3.5" />
                    </div>

                    <span>
                      LinkedIn Profile
                    </span>
                  </a>

                  {/* EMAIL */}

                  <a
                    href="mailto:anmolmadan20@gmail.com"
                    className="
                      flex
                      items-center
                      gap-3
                      text-sm
                      text-neutral-600
                      transition-colors
                      duration-300
                      hover:text-black
                      dark:text-neutral-400
                      dark:hover:text-white
                    "
                  >
                    <div
                      className="
                        flex
                        h-8
                        w-8
                        items-center
                        justify-center
                        rounded-full
                        border
                        border-neutral-200
                        bg-neutral-50
                        dark:border-neutral-800
                        dark:bg-neutral-900
                      "
                    >
                      <Mail className="h-3.5 w-3.5" />
                    </div>

                    <span>
                      anmolmadan20@gmail.com
                    </span>
                  </a>

                  {/* PHONE */}

                  <a
                    href="tel:+919876543210"
                    className="
                      flex
                      items-center
                      gap-3
                      text-sm
                      text-neutral-600
                      transition-colors
                      duration-300
                      hover:text-black
                      dark:text-neutral-400
                      dark:hover:text-white
                    "
                  >
                    <div
                      className="
                        flex
                        h-8
                        w-8
                        items-center
                        justify-center
                        rounded-full
                        border
                        border-neutral-200
                        bg-neutral-50
                        dark:border-neutral-800
                        dark:bg-neutral-900
                      "
                    >
                      <Phone className="h-3.5 w-3.5" />
                    </div>

                    <span>
                      +91 98765 43210
                    </span>
                  </a>

                  {/* INSTAGRAM */}

                  <a
                    href="https://www.instagram.com/anmolxmadan/"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="
                      flex
                      items-center
                      gap-3
                      text-sm
                      text-neutral-600
                      transition-colors
                      duration-300
                      hover:text-black
                      dark:text-neutral-400
                      dark:hover:text-white
                    "
                  >
                    <div
                      className="
                        flex
                        h-8
                        w-8
                        items-center
                        justify-center
                        rounded-full
                        border
                        border-neutral-200
                        bg-neutral-50
                        dark:border-neutral-800
                        dark:bg-neutral-900
                      "
                    >
                      <InstagramIcon className="h-3.5 w-3.5" />
                    </div>

                    <span>
                      Instagram Updates
                    </span>
                  </a>
                </>
              )}
            </div>
          </div>
        </div>

        {/* =================================================
            BOTTOM
        ================================================= */}

        <div
          className="
            mt-20
            border-t
            border-black/[0.08]
            pt-7
            dark:border-white/[0.08]
          "
        >
          <div
            className="
              flex
              flex-col
              items-start
              justify-between
              gap-5
              text-[11px]
              text-neutral-400
              sm:flex-row
              sm:items-center
            "
          >
            <p>
              © 2026 Anmol Madan. All Rights Reserved.
            </p>

            <div
              className="
                flex
                flex-wrap
                items-center
                gap-3
              "
            >
              <span>anmolmadan.in</span>

              <span className="text-neutral-200 dark:text-neutral-700">
                •
              </span>

              <span>
                Chandigarh, India
              </span>

              <span className="text-neutral-200 dark:text-neutral-700">
                •
              </span>

              <CalButton
                className="
                  inline-flex
                  items-center
                  gap-1
                  text-[11px]
                  text-neutral-400
                  transition-colors
                  duration-300
                  hover:text-black
                  dark:text-neutral-500
                  dark:hover:text-white
                "
              >
                Book a Call
                <ArrowUpRight className="h-3.5 w-3.5" />
              </CalButton>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
}

// src/lib/components/visitor/Footer.svelte
<script lang="ts">
	import type { ContactLink } from "$lib/data/contact";
	import { ArrowUpRight, Mail, Phone, Calendar } from "@lucide/svelte";
	import SocialIcons from "$lib/components/shared/SocialIcons.svelte";

	interface Props {
		links: ContactLink[];
		onBookCall: () => void;
	}

	let { links = [], onBookCall }: Props = $props();

	function scrollToSection(id: string) {
		const target = document.querySelector(id);
		if (target) {
			target.scrollIntoView({ behavior: "smooth", block: "start" });
		}
	}

	function scrollToTop() {
		window.scrollTo({ top: 0, behavior: "smooth" });
	}
</script>

<footer
	class="font-['Instrument_Sans',sans-serif] border-t border-black/[0.08] bg-white text-black dark:border-white/[0.08] dark:bg-black dark:text-white"
>
	<!-- PRE-FOOTER CTA -->
	<div class="border-b border-white/[0.08] bg-neutral-900 text-white">
		<div
			class="mx-auto flex max-w-[1500px] flex-col items-start justify-between gap-8 px-6 py-16 sm:px-8 lg:flex-row lg:items-center lg:px-12 xl:px-16"
		>
			<div class="max-w-2xl">
				<span
					class="text-[10px] font-semibold uppercase tracking-[0.3em] text-neutral-400"
				>
					Work Together
				</span>

				<h2
					class="mt-3 text-3xl font-medium tracking-[-0.03em] sm:text-4xl lg:text-5xl text-white"
				>
					Ready to create an unforgettable session?
				</h2>

				<p class="mt-4 text-sm text-neutral-400 sm:text-base">
					Available for corporate cybersecurity training, college workshops, and keynote
					speaking across India & online.
				</p>
			</div>

			<!-- BOOK A CALL -->
			<div class="flex flex-wrap items-center gap-4">
				<button
					type="button"
					onclick={onBookCall}
					class="inline-flex items-center gap-2 rounded-full bg-white px-8 py-4 text-xs font-semibold uppercase tracking-[0.1em] text-black transition-all duration-300 hover:scale-105 hover:bg-neutral-100 active:scale-95 cursor-pointer"
				>
					Book a Call
					<ArrowUpRight class="h-4 w-4" />
				</button>
			</div>
		</div>
	</div>

	<!-- MAIN FOOTER -->
	<div
		class="mx-auto max-w-[1500px] px-6 py-20 sm:px-8 lg:px-12 xl:px-16"
	>
		<div
			class="grid gap-16 sm:grid-cols-2 lg:grid-cols-[1.3fr_0.7fr_0.8fr_1fr] lg:gap-12 xl:gap-14"
		>
			<!-- BRAND -->
			<div>
				<button
					type="button"
					onclick={scrollToTop}
					class="group cursor-pointer border-none bg-transparent p-0 text-left outline-none"
				>
					<div
						class="text-[26px] font-semibold leading-none tracking-[0.25em] text-black transition-opacity duration-300 group-hover:opacity-60 dark:text-white"
					>
						ANMOL
					</div>
					<p
						class="mt-1.5 text-[8px] font-medium leading-none tracking-[0.48em] text-neutral-400"
					>
						MADAN
					</p>
				</button>

				<div
					class="mt-8 max-w-[290px] space-y-2 text-[14px] leading-6 text-neutral-500 dark:text-neutral-400"
				>
					<p class="font-medium text-neutral-800 dark:text-neutral-200">
						Cybersecurity Trainer & Motivational Speaker
					</p>
					<p>Based in Chandigarh, India</p>
					<p>Delivering sessions Pan-India & Online</p>
				</div>

				<div class="mt-6 flex items-center gap-2.5">
					<a
						href="https://www.linkedin.com/in/anmolmadan"
						target="_blank"
						rel="noopener noreferrer"
						aria-label="LinkedIn"
						class="flex h-8 w-8 items-center justify-center rounded-full border border-neutral-200 dark:border-neutral-800 bg-neutral-50 dark:bg-neutral-900 text-neutral-600 dark:text-neutral-400 transition-colors hover:border-black hover:text-black dark:hover:border-white dark:hover:text-white"
					>
						<SocialIcons name="Linkedin" size={13} class="h-3.5 w-3.5" />
					</a>
					<a
						href="https://wa.me/919914444589"
						target="_blank"
						rel="noopener noreferrer"
						aria-label="WhatsApp"
						class="flex h-8 w-8 items-center justify-center rounded-full border border-neutral-200 dark:border-neutral-800 bg-neutral-50 dark:bg-neutral-900 text-neutral-600 dark:text-neutral-400 transition-colors hover:border-black hover:text-black dark:hover:border-white dark:hover:text-white"
					>
						<SocialIcons name="WhatsApp" size={13} class="h-3.5 w-3.5" />
					</a>
					<a
						href="https://www.instagram.com/anmolmadanofficial"
						target="_blank"
						rel="noopener noreferrer"
						aria-label="Instagram"
						class="flex h-8 w-8 items-center justify-center rounded-full border border-neutral-200 dark:border-neutral-800 bg-neutral-50 dark:bg-neutral-900 text-neutral-600 dark:text-neutral-400 transition-colors hover:border-black hover:text-black dark:hover:border-white dark:hover:text-white"
					>
						<SocialIcons name="Instagram" size={13} class="h-3.5 w-3.5" />
					</a>
				</div>
			</div>

			<!-- EXPLORE -->
			<div>
				<h3
					class="mb-7 text-[10px] font-semibold uppercase tracking-[0.28em] text-neutral-400"
				>
					Explore
				</h3>

				<div
					class="flex flex-col gap-3.5 text-[14px] text-neutral-600 dark:text-neutral-400"
				>
					<button
						type="button"
						onclick={scrollToTop}
						class="w-fit cursor-pointer border-none bg-transparent p-0 text-left transition-colors duration-300 hover:text-black dark:hover:text-white"
					>
						Home
					</button>
					<button
						type="button"
						onclick={() => scrollToSection("#about")}
						class="w-fit cursor-pointer border-none bg-transparent p-0 text-left transition-colors duration-300 hover:text-black dark:hover:text-white"
					>
						About
					</button>
					<button
						type="button"
						onclick={() => scrollToSection("#testimonials")}
						class="w-fit cursor-pointer border-none bg-transparent p-0 text-left transition-colors duration-300 hover:text-black dark:hover:text-white"
					>
						Testimonials
					</button>
					<button
						type="button"
						onclick={() => scrollToSection("#services")}
						class="w-fit cursor-pointer border-none bg-transparent p-0 text-left transition-colors duration-300 hover:text-black dark:hover:text-white"
					>
						Services
					</button>
					<button
						type="button"
						onclick={() => scrollToSection("#vision")}
						class="w-fit cursor-pointer border-none bg-transparent p-0 text-left transition-colors duration-300 hover:text-black dark:hover:text-white"
					>
						Vision
					</button>
					<button
						type="button"
						onclick={() => scrollToSection("#note")}
						class="w-fit cursor-pointer border-none bg-transparent p-0 text-left transition-colors duration-300 hover:text-black dark:hover:text-white"
					>
						Notes
					</button>
				</div>
			</div>

			<!-- KEY EXPERTISE -->
			<div>
				<h3
					class="mb-7 text-[10px] font-semibold uppercase tracking-[0.28em] text-neutral-400"
				>
					Key Expertise
				</h3>

				<ul
					class="space-y-3.5 text-[14px] leading-6 text-neutral-600 dark:text-neutral-400"
				>
					<li>Corporate Cybersecurity</li>
					<li>Ethical Hacking Workshops</li>
					<li>Motivational Keynotes</li>
					<li>Executive Threat Defense</li>
					<li>Student Mentorship</li>
				</ul>
			</div>

			<!-- CONNECT DIRECTLY -->
			<div>
				<h3
					class="mb-7 text-[10px] font-semibold uppercase tracking-[0.28em] text-neutral-400"
				>
					Connect Directly
				</h3>

				<div class="flex flex-col gap-4">
					{#each links as link}
						{@const isBooking = link.id === "booking" || link.url.includes("cal.com")}
						{#if isBooking}
							<button
								type="button"
								onclick={onBookCall}
								class="flex items-center gap-3 text-sm text-neutral-600 transition-colors duration-300 hover:text-black dark:text-neutral-400 dark:hover:text-white cursor-pointer text-left"
							>
								<div
									class="flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-neutral-200 bg-neutral-50 dark:border-neutral-800 dark:bg-neutral-900"
								>
									<Calendar size={14} />
								</div>
								<span class="truncate">{link.label}</span>
							</button>
						{:else}
							{@const isSpecial = link.url.startsWith("mailto:") || link.url.startsWith("tel:")}
							<a
								href={link.url}
								target={isSpecial ? undefined : "_blank"}
								rel={isSpecial ? undefined : "noopener noreferrer"}
								class="flex items-center gap-3 text-sm text-neutral-600 transition-colors duration-300 hover:text-black dark:text-neutral-400 dark:hover:text-white"
							>
								<div
									class="flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-neutral-200 bg-neutral-50 dark:border-neutral-800 dark:bg-neutral-900"
								>
									{#if link.iconName === "Linkedin"}
										<SocialIcons name="Linkedin" size={14} class="h-3.5 w-3.5" />
									{:else if link.iconName === "Instagram"}
										<SocialIcons name="Instagram" size={14} class="h-3.5 w-3.5" />
									{:else if link.iconName === "WhatsApp"}
										<SocialIcons name="WhatsApp" size={14} class="h-3.5 w-3.5" />
									{:else if link.iconName === "Mail"}
										<Mail size={14} />
									{:else if link.iconName === "Phone"}
										<Phone size={14} />
									{:else}
										<Calendar size={14} />
									{/if}
								</div>
								<span class="truncate">{link.label}</span>
							</a>
						{/if}
					{/each}
				</div>
			</div>
		</div>

		<!-- BOTTOM BAR -->
		<div
			class="mt-16 flex flex-col items-center justify-between gap-4 border-t border-neutral-200/80 dark:border-neutral-800 pt-8 sm:flex-row text-xs text-neutral-500 dark:text-neutral-400"
		>
			<p>© {new Date().getFullYear()} Anmol Madan. All rights reserved.</p>
			<p class="text-neutral-400">Cybersecurity Specialist & Motivational Speaker</p>
		</div>
	</div>
</footer>
