// src/components/visitor/layout/Navbar.tsx
"use client";

import { Menu, X } from "lucide-react";
import { AnimatePresence, motion } from "framer-motion";
import { useEffect, useState } from "react";
import { Instrument_Sans } from "next/font/google";

/* =========================================================
   FONT
========================================================= */

const navbarFont = Instrument_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

/* =========================================================
   NAVIGATION
========================================================= */

const navItems = [
  { label: "About", href: "#about" },
  { label: "Vision", href: "#vision" },
  { label: "Experience", href: "#experience" },
  { label: "Testimonials", href: "#testimonials" },
];

/* =========================================================
   NAVBAR
========================================================= */

export default function Navbar() {
  const [open, setOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);

  /* =======================================================
     SCROLL DETECTION
  ======================================================= */

  useEffect(() => {
    const handleScroll = () => {
      setScrolled(window.scrollY > 12);
    };

    handleScroll();

    window.addEventListener("scroll", handleScroll, {
      passive: true,
    });

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  /* =======================================================
     SMOOTH SCROLL
  ======================================================= */

  const scrollToSection = (id: string) => {
    const section = document.querySelector(id);

    if (!section) {
      setOpen(false);
      return;
    }

    section.scrollIntoView({
      behavior: "smooth",
      block: "start",
    });

    setOpen(false);
  };

  return (
    <>
      {/* =====================================================
          MAIN NAVBAR
      ===================================================== */}

      <motion.nav
        initial={{ y: -70, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{
          duration: 0.65,
          ease: [0.22, 1, 0.36, 1],
        }}
        className={`
          ${navbarFont.className}

          fixed
          inset-x-0
          top-0
          z-[100]

          w-full

          border-none
          outline-none
          shadow-none
        `}
      >
        <div
          className={`
            grid
            w-full
            grid-cols-3
            items-center

            px-6
            sm:px-8
            lg:px-10
            xl:px-12

            transition-all
            duration-500
            ease-out

            ${
              scrolled
                ? `
                  h-[68px]
                  bg-white/70
                  backdrop-blur-xl
                  backdrop-saturate-150
                `
                : `
                  h-[82px]
                  bg-transparent
                  backdrop-blur-0
                `
            }
          `}
        >
          {/* =================================================
              LEFT — LOGO
          ================================================= */}

          <div className="flex justify-start">
            <button
              type="button"
              onClick={() => scrollToSection("#hero")}
              aria-label="Go to homepage"
              className="
                relative
                z-[110]
                shrink-0

                border-none
                bg-transparent
                p-0

                text-left
                outline-none

                group
              "
            >
              <h1
                className="
                  text-[24px]
                  font-semibold
                  leading-none
                  tracking-[0.24em]
                  text-black

                  transition-opacity
                  duration-300
                  group-hover:opacity-70

                  sm:text-[27px]
                "
              >
                ANMOL
              </h1>

              <p
                className="
                  mt-[5px]

                  text-[8px]
                  font-medium
                  leading-none

                  tracking-[0.48em]

                  text-neutral-500

                  sm:text-[9px]
                "
              >
                MADAN
              </p>
            </button>
          </div>

          {/* =================================================
              CENTER — DESKTOP NAVIGATION
          ================================================= */}

          <div
            className="
              hidden
              items-center
              justify-center

              gap-7
              xl:gap-9

              lg:flex
            "
          >
            {navItems.map((item) => (
              <button
                key={item.label}
                type="button"
                onClick={() => scrollToSection(item.href)}
                className="
                  group
                  relative

                  whitespace-nowrap

                  border-none
                  bg-transparent
                  p-0

                  text-[10px]
                  font-medium
                  uppercase

                  tracking-[0.18em]

                  text-neutral-600

                  outline-none

                  transition-colors
                  duration-300

                  hover:text-black
                "
              >
                {item.label}

                {/* Underline */}

                <span
                  className="
                    absolute

                    -bottom-[7px]
                    left-0

                    h-px
                    w-0

                    bg-black

                    transition-all
                    duration-300
                    ease-out

                    group-hover:w-full
                  "
                />
              </button>
            ))}
          </div>

          {/* =================================================
              RIGHT — CONTACT
          ================================================= */}

          <div className="flex justify-end">
            <button
              type="button"
              onClick={() => scrollToSection("#contact")}
              className="
                relative
                z-[110]

                hidden
                shrink-0

                min-w-[132px]

                rounded-full

                border-none
                bg-black

                px-6
                py-[11px]

                text-[11px]
                font-medium

                tracking-[-0.01em]

                text-white

                outline-none

                transition-all
                duration-300

                hover:scale-[1.035]
                hover:bg-neutral-800

                active:scale-[0.98]

                lg:block
              "
            >
              Contact Now →
            </button>
          </div>

          {/* =================================================
              MOBILE MENU BUTTON
          ================================================= */}

          <button
            type="button"
            onClick={() => setOpen((prev) => !prev)}
            aria-label={open ? "Close menu" : "Open menu"}
            aria-expanded={open}
            className="
              relative
              z-[110]

              justify-self-end

              border-none
              bg-transparent
              p-1

              text-black

              outline-none

              lg:hidden
            "
          >
            <AnimatePresence
              mode="wait"
              initial={false}
            >
              {open ? (
                <motion.div
                  key="close"
                  initial={{
                    opacity: 0,
                    rotate: -45,
                    scale: 0.8,
                  }}
                  animate={{
                    opacity: 1,
                    rotate: 0,
                    scale: 1,
                  }}
                  exit={{
                    opacity: 0,
                    rotate: 45,
                    scale: 0.8,
                  }}
                  transition={{
                    duration: 0.2,
                  }}
                >
                  <X
                    size={25}
                    strokeWidth={1.7}
                  />
                </motion.div>
              ) : (
                <motion.div
                  key="menu"
                  initial={{
                    opacity: 0,
                    rotate: 45,
                    scale: 0.8,
                  }}
                  animate={{
                    opacity: 1,
                    rotate: 0,
                    scale: 1,
                  }}
                  exit={{
                    opacity: 0,
                    rotate: -45,
                    scale: 0.8,
                  }}
                  transition={{
                    duration: 0.2,
                  }}
                >
                  <Menu
                    size={25}
                    strokeWidth={1.7}
                  />
                </motion.div>
              )}
            </AnimatePresence>
          </button>
        </div>
      </motion.nav>

      {/* =====================================================
          MOBILE MENU
      ===================================================== */}

      <AnimatePresence>
        {open && (
          <>
            {/* Background overlay */}

            <motion.div
              initial={{
                opacity: 0,
              }}
              animate={{
                opacity: 1,
              }}
              exit={{
                opacity: 0,
              }}
              transition={{
                duration: 0.3,
              }}
              onClick={() => setOpen(false)}
              className="
                fixed
                inset-0
                z-[80]

                bg-black/20
                backdrop-blur-sm

                lg:hidden
              "
            />

            {/* Menu panel */}

            <motion.div
              initial={{
                opacity: 0,
                x: "100%",
              }}
              animate={{
                opacity: 1,
                x: 0,
              }}
              exit={{
                opacity: 0,
                x: "100%",
              }}
              transition={{
                duration: 0.45,
                ease: [0.22, 1, 0.36, 1],
              }}
              className={`
                ${navbarFont.className}

                fixed
                inset-y-0
                right-0

                z-[90]

                w-[88%]
                max-w-[420px]

                bg-white

                pt-28

                shadow-[-30px_0_80px_rgba(0,0,0,0.12)]

                lg:hidden
              `}
            >
              <div className="flex h-full flex-col px-8">
                {/* Small label */}

                <motion.p
                  initial={{
                    opacity: 0,
                    y: 10,
                  }}
                  animate={{
                    opacity: 1,
                    y: 0,
                  }}
                  transition={{
                    delay: 0.1,
                  }}
                  className="
                    mb-8

                    text-[9px]
                    font-semibold
                    uppercase

                    tracking-[0.32em]

                    text-neutral-400
                  "
                >
                  Navigation
                </motion.p>

                {/* Navigation */}

                <div className="flex flex-col">
                  {navItems.map((item, index) => (
                    <motion.button
                      key={item.label}
                      type="button"
                      onClick={() =>
                        scrollToSection(item.href)
                      }
                      initial={{
                        opacity: 0,
                        x: 20,
                      }}
                      animate={{
                        opacity: 1,
                        x: 0,
                      }}
                      transition={{
                        delay:
                          0.08 +
                          index * 0.045,
                        duration: 0.35,
                        ease: [
                          0.22,
                          1,
                          0.36,
                          1,
                        ],
                      }}
                      className="
                        group

                        flex
                        items-center
                        justify-between

                        border-none
                        border-b
                        border-neutral-100

                        bg-transparent

                        py-4

                        text-left

                        text-lg
                        font-medium

                        tracking-[0.05em]

                        text-black

                        outline-none
                      "
                    >
                      <span>
                        {item.label}
                      </span>

                      <span
                        className="
                          text-neutral-300

                          transition-all
                          duration-300

                          group-hover:translate-x-1
                          group-hover:text-black
                        "
                      >
                        →
                      </span>
                    </motion.button>
                  ))}
                </div>

                {/* Contact */}

                <motion.button
                  type="button"
                  onClick={() =>
                    scrollToSection("#contact")
                  }
                  initial={{
                    opacity: 0,
                    y: 20,
                  }}
                  animate={{
                    opacity: 1,
                    y: 0,
                  }}
                  transition={{
                    delay:
                      0.08 +
                      navItems.length * 0.045 +
                      0.1,
                  }}
                  className="
                    mt-10

                    w-full

                    rounded-full

                    border-none
                    bg-black

                    px-8
                    py-4

                    text-sm
                    font-medium

                    text-white

                    outline-none

                    transition-transform
                    duration-300

                    active:scale-[0.98]
                  "
                >
                  Contact Now →
                </motion.button>

                {/* Bottom detail */}

                <div className="mt-auto pb-8">
                  <div
                    className="
                      h-px
                      w-full
                      bg-neutral-100
                    "
                  />

                  <p
                    className="
                      mt-5

                      text-[9px]
                      font-medium
                      uppercase

                      tracking-[0.3em]

                      text-neutral-400
                    "
                  >
                    ANMOL MADAN
                  </p>
                </div>
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </>
  );
}

// src/lib/components/visitor/Navbar.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import { Menu, X, Calendar } from "@lucide/svelte";

	interface Props {
		onBookCall: () => void;
	}

	let { onBookCall }: Props = $props();

	let scrollY = $state(0);
	let isMobile = $state(false);
	let mobileMenuOpen = $state(false);
	let activeSection = $state("");
	let isDark = $state(false);

	const navItems = [
		{ label: "About", href: "#about", id: "about" },
		{ label: "Testimonials", href: "#testimonials", id: "testimonials" },
		{ label: "Services", href: "#services", id: "services" },
		{ label: "Vision", href: "#vision", id: "vision" },
		{ label: "Note", href: "#note", id: "note" }
	];

	// Scroll interpolation (0 -> 300px)
	let scrollProgress = $derived(Math.min(1, Math.max(0, scrollY / 260)));
	let desktopMarginX = $derived(scrollProgress * 180); // margin on each side for pill effect
	let topOffset = $derived(scrollProgress * 14);
	let containerHeight = $derived(80 - scrollProgress * 26); // 80px -> 54px
	let borderRadius = $derived(scrollProgress * 9999);
	let bgOpacity = $derived(0.6 + scrollProgress * 0.35);
	let shadowOpacity = $derived(scrollProgress * 0.12);
	let borderOpacity = $derived(0.04 + scrollProgress * 0.08);

	onMount(() => {
		isDark = document.documentElement.classList.contains("dark");

		const observer = new MutationObserver(() => {
			isDark = document.documentElement.classList.contains("dark");
		});
		observer.observe(document.documentElement, { attributes: true, attributeFilter: ["class"] });

		function handleScroll() {
			scrollY = window.scrollY;
			updateActiveSection();
		}

		function handleResize() {
			isMobile = window.innerWidth < 1024;
		}

		function updateActiveSection() {
			const sections = navItems
				.map((item) => document.getElementById(item.id))
				.filter(Boolean) as HTMLElement[];

			const activationPoint = window.innerHeight * 0.35;

			for (const section of sections) {
				const rect = section.getBoundingClientRect();
				if (rect.top <= activationPoint && rect.bottom >= activationPoint) {
					activeSection = section.id;
					return;
				}
			}

			if (window.scrollY < 300) {
				activeSection = "";
			}
		}

		handleResize();
		handleScroll();

		window.addEventListener("scroll", handleScroll, { passive: true });
		window.addEventListener("resize", handleResize);

		return () => {
			observer.disconnect();
			window.removeEventListener("scroll", handleScroll);
			window.removeEventListener("resize", handleResize);
		};
	});

	function scrollTo(href: string) {
		mobileMenuOpen = false;
		const target = document.querySelector(href);
		if (target) {
			target.scrollIntoView({ behavior: "smooth", block: "start" });
		}
	}

	function scrollToTop() {
		mobileMenuOpen = false;
		window.scrollTo({ top: 0, behavior: "smooth" });
	}
</script>

<!-- NAVBAR CONTAINER -->
<nav
	class="fixed inset-x-0 z-[100] pointer-events-none transition-all duration-300 ease-out font-['Instrument_Sans',sans-serif]"
	style="top: {isMobile ? (scrollY > 50 ? 8 : 0) : topOffset}px;"
>
	<div
		class="pointer-events-auto mx-auto flex items-center justify-between overflow-hidden transition-all duration-300 ease-out {isMobile
			? scrollY > 50
				? 'mx-3 rounded-full px-4 sm:px-6'
				: 'w-full px-6'
			: 'px-8'}"
		style="{!isMobile
			? `max-width: calc(100% - ${desktopMarginX * 2}px); border-radius: ${borderRadius}px;`
			: ''} height: {isMobile
			? scrollY > 50
				? 56
				: 68
			: containerHeight}px; background-color: rgba({isDark
			? '0, 0, 0'
			: '255, 255, 255'}, {bgOpacity}); backdrop-filter: blur(20px); -webkit-backdrop-filter: blur(20px); border: 1px solid rgba({isDark
			? '255, 255, 255'
			: '0, 0, 0'}, {borderOpacity}); box-shadow: 0 10px 30px rgba(0, 0, 0, {shadowOpacity});"
	>
		<!-- LEFT: LOGO -->
		<div class="flex flex-1 items-center justify-start">
			<button
				type="button"
				onclick={scrollToTop}
				aria-label="Go to homepage"
				class="group relative z-[110] flex items-center cursor-pointer border-none bg-transparent p-0 outline-none"
			>
				<img
					src="/anmol_logo.png"
					alt="Anmol Madan"
					class="h-7 sm:h-8 lg:h-9 w-auto transition-all duration-300 group-hover:opacity-75"
				/>
			</button>
		</div>

		<!-- CENTER: DESKTOP NAV ITEMS -->
		<div class="hidden lg:flex shrink-0 items-center justify-center gap-7 xl:gap-8">
			{#each navItems as item}
				{@const isActive = activeSection === item.id}
				<button
					type="button"
					onclick={() => scrollTo(item.href)}
					class="group relative whitespace-nowrap border-none bg-transparent p-0 text-[11px] font-semibold uppercase tracking-[0.18em] outline-none transition-colors duration-300 cursor-pointer {isActive
						? 'text-black dark:text-white'
						: 'text-neutral-500 dark:text-neutral-400 hover:text-black dark:hover:text-white'}"
				>
					{item.label}

					<!-- Active / Hover Underline -->
					<span
						class="absolute -bottom-[5px] left-0 h-[1.5px] bg-black dark:bg-white transition-all duration-300 ease-out {isActive
							? 'w-full'
							: 'w-0 group-hover:w-full'}"
					></span>
				</button>
			{/each}
		</div>

		<!-- RIGHT: ACTIONS -->
		<div class="flex flex-1 items-center justify-end gap-3">
			<!-- Book a Call Button -->
			<button
				type="button"
				onclick={onBookCall}
				class="hidden sm:inline-flex items-center gap-2 rounded-full bg-black dark:bg-white px-5 py-2 text-[11px] font-semibold uppercase tracking-[0.12em] text-white dark:text-black transition-all duration-200 hover:opacity-85 active:scale-95 cursor-pointer shadow-sm"
			>
				<span>Book a Call</span>
			</button>

			<!-- Mobile Menu Hamburger -->
			<button
				type="button"
				onclick={() => (mobileMenuOpen = !mobileMenuOpen)}
				aria-label={mobileMenuOpen ? "Close menu" : "Open menu"}
				class="flex lg:hidden h-9 w-9 items-center justify-center rounded-full border border-neutral-200 dark:border-neutral-800 bg-white/90 dark:bg-neutral-900/90 text-black dark:text-white transition-colors cursor-pointer"
			>
				{#if mobileMenuOpen}
					<X size={18} />
				{:else}
					<Menu size={18} />
				{/if}
			</button>
		</div>
	</div>

	<!-- MOBILE DROPDOWN DRAWER -->
	{#if mobileMenuOpen}
		<div
			class="pointer-events-auto mx-3 mt-2 rounded-3xl border border-neutral-200 dark:border-neutral-800 bg-white/95 dark:bg-black/95 p-6 shadow-2xl backdrop-blur-xl lg:hidden animate-in fade-in slide-in-from-top-4 duration-200"
		>
			<div class="flex flex-col gap-4">
				{#each navItems as item}
					{@const isActive = activeSection === item.id}
					<button
						type="button"
						onclick={() => scrollTo(item.href)}
						class="flex items-center justify-between py-2 text-base font-semibold uppercase tracking-wider text-left transition-colors cursor-pointer {isActive
							? 'text-black dark:text-white'
							: 'text-neutral-500 dark:text-neutral-400 hover:text-black dark:hover:text-white'}"
					>
						<span>{item.label}</span>
						{#if isActive}
							<span class="h-1.5 w-1.5 rounded-full bg-black dark:bg-white"></span>
						{/if}
					</button>
				{/each}

				<div class="mt-4 border-t border-neutral-100 dark:border-neutral-800 pt-4">
					<button
						type="button"
						onclick={() => {
							mobileMenuOpen = false;
							onBookCall();
						}}
						class="w-full inline-flex items-center justify-center gap-2 rounded-full bg-black dark:bg-white px-5 py-3 text-xs font-semibold uppercase tracking-wider text-white dark:text-black cursor-pointer"
					>
						<Calendar size={14} />
						<span>Book a Call</span>
					</button>
				</div>
			</div>
		</div>
	{/if}
</nav>
